version: '2.4'  # The last version of Docker Compose file format that directly supports mem_limit and cpus
services:
  counter-service:
    container_name: counter-service-exercise
    image: 533402247589.dkr.ecr.ap-southeast-1.amazonaws.com/counter-service:latest
    volumes:
      - ./data:/data
    ports:
      - "85:8080"
    restart: always
    mem_limit: 256M
    cpus: 0.5
